apiVersion: v1
kind: Namespace
metadata:
  name: symfony-kubernetes

---

apiVersion: v1
kind: Service
metadata:
  namespace: symfony-kubernetes
  name: symfony-service
spec:
  selector:
    app: symfony
  type: ClusterIP  # Change to ClusterIP
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: symfony-kubernetes
  name: symfony-deployment
  labels:
    app: symfony
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony
  template:
    metadata:
      labels:
        app: symfony
    spec:
      containers:
        - name: symfony
          image: ivanaki/jenkins-example-symfony:latest
          ports:
            - containerPort: 80

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: symfony-kubernetes
  name: symfony-ingress
spec:
  rules:
    - host: 7244ee91331c.websh.mylabserver.com
      http:
        paths:
          - path: /symm
            pathType: Prefix
            backend:
              serviceName: symfony-service
              servicePort: 8087






# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: jenkins-example-symfony
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: jenkins-example-symfony
#   template:
#     metadata:
#       labels:
#         app: jenkins-example-symfony
#     spec:
#       containers:
#       - name: jenkins-example-symfony
#         image: ivanaki/jenkins-example-symfony:latest
#         ports:
#         - containerPort: 80

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: jenkins-example-symfony
# spec:
#   selector:
#     app: jenkins-example-symfony
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#       nodePort: 30011  # Specify the NodePort value (any valid port number)
#   type: NodePort

